version: "3"

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    container_name: fresh_market_shop_pg
    environment:
      - "POSTGRES_DB=${PG_DB}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  migrator:
    container_name: fresh_market_shop_migrator
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
